package ParamTest;


/**
* ParamTest/my_structHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ParamTest.idl
* Friday, 1 March 2019 15:15:56 o'clock GMT
*/

abstract public class my_structHelper
{
  private static String  _id = "IDL:ParamTest/my_struct:1.0";

  public static void insert (org.omg.CORBA.Any a, ParamTest.my_struct that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ParamTest.my_struct extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "s",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "l",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ObjectHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "o",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ParamTest.my_structHelper.id (), "my_struct", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ParamTest.my_struct read (org.omg.CORBA.portable.InputStream istream)
  {
    ParamTest.my_struct value = new ParamTest.my_struct ();
    value.s = istream.read_string ();
    value.l = istream.read_long ();
    value.o = org.omg.CORBA.ObjectHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ParamTest.my_struct value)
  {
    ostream.write_string (value.s);
    ostream.write_long (value.l);
    org.omg.CORBA.ObjectHelper.write (ostream, value.o);
  }

}
