package ParamTest;

/**
* ParamTest/my_structHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ParamTest.idl
* Friday, 1 March 2019 15:15:56 o'clock GMT
*/

public final class my_structHolder implements org.omg.CORBA.portable.Streamable
{
  public ParamTest.my_struct value = null;

  public my_structHolder ()
  {
  }

  public my_structHolder (ParamTest.my_struct initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParamTest.my_structHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParamTest.my_structHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParamTest.my_structHelper.type ();
  }

}
