package ParamTest;


/**
* ParamTest/my_struct.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ParamTest.idl
* Friday, 1 March 2019 15:15:56 o'clock GMT
*/

public final class my_struct implements org.omg.CORBA.portable.IDLEntity
{
  public String s = null;
  public int l = (int)0;
  public org.omg.CORBA.Object o = null;

  public my_struct ()
  {
  } // ctor

  public my_struct (String _s, int _l, org.omg.CORBA.Object _o)
  {
    s = _s;
    l = _l;
    o = _o;
  } // ctor

} // class my_struct
