package ParamTest;


/**
* ParamTest/MyServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ParamTest.idl
* Friday, 1 March 2019 15:15:56 o'clock GMT
*/

abstract public class MyServerHelper
{
  private static String  _id = "IDL:ParamTest/MyServer:1.0";

  public static void insert (org.omg.CORBA.Any a, ParamTest.MyServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ParamTest.MyServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ParamTest.MyServerHelper.id (), "MyServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ParamTest.MyServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MyServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ParamTest.MyServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ParamTest.MyServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ParamTest.MyServer)
      return (ParamTest.MyServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ParamTest._MyServerStub stub = new ParamTest._MyServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ParamTest.MyServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ParamTest.MyServer)
      return (ParamTest.MyServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ParamTest._MyServerStub stub = new ParamTest._MyServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
