package ParamTest;

/**
* ParamTest/MyServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ParamTest.idl
* Friday, 1 March 2019 15:15:56 o'clock GMT
*/

public final class MyServerHolder implements org.omg.CORBA.portable.Streamable
{
  public ParamTest.MyServer value = null;

  public MyServerHolder ()
  {
  }

  public MyServerHolder (ParamTest.MyServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParamTest.MyServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParamTest.MyServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParamTest.MyServerHelper.type ();
  }

}
