package ParamTest;


/**
* ParamTest/stringArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ParamTest.idl
* Friday, 1 March 2019 15:15:56 o'clock GMT
*/

public final class stringArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public stringArrayHolder ()
  {
  }

  public stringArrayHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParamTest.stringArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParamTest.stringArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParamTest.stringArrayHelper.type ();
  }

}
