package ParamTest;


/**
* ParamTest/stringCubeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ParamTest.idl
* Friday, 1 March 2019 15:15:56 o'clock GMT
*/

public final class stringCubeHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[][][] = null;

  public stringCubeHolder ()
  {
  }

  public stringCubeHolder (String[][][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ParamTest.stringCubeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ParamTest.stringCubeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ParamTest.stringCubeHelper.type ();
  }

}
